# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Docs publishing

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install sphinx-toolbox sphinx-autobuild myst-parser furo sphinx-copybutton sphinxext-opengraph matplotlib sphinx-sitemap sphinxcontrib-katex
    - name: Build docs html
      run: |
        cd docs
        make html
    - name: Upload docs to S3
      uses: shallwefootball/s3-upload-action@v1.3.3
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
        source_dir: 'docs/build/html'
        destination_dir: ''
        
